title: "Ruihan’s Log"
description: "Notes on Embodied Intelligence, World Models, and Robotics."
url: "https://daisy-butter.github.io"   # 你的 GitHub 用户域
baseurl: "/ruihanwu.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
include_navbar_skip_links: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 作者信息
author:
  name: "Ruihan Wu"
  avatar: "/assets/images/avatar.jpg"
  bio: "Researching Embodied Intelligence and Robotics Learning."
  location: "Shanghai, China"
  email: "22307140084@m.fudan.edu.cn"
  links:
    - label: "GitHub"
      url: "https://github.com/Daisy-butter"

# Markdown 与数学公式
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# 语法高亮
highlighter: rouge

# 分页
paginate: 5
paginate_path: "/page:num/"

# SASS
sass:
  style: compressed
  load_paths:
    - _sass

# 其他
exclude:
  - Gemfile.lock

collections:
  posts:
    output: true
    permalink: /:title/

include:
  - _posts
  - _layouts
  - index.md
  - about.md