# 基本信息
title: "Embodied Intelligence Notes"
description: "Notes on Embodied Intelligence"
url: "https://github.com/Daisy-butter/ruihanwu.github.io" # 改成你的仓库 URL
baseurl: ""  # leave empty for github.io sites

# 主题（使用远程 minimal-mistakes，免去主题源码）
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "default"
include_navbar_skip_links: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 作者信息
author:
  name: "Daisy-Butter"
  avatar: "/assets/images/avatar.jpg"
  bio: "研究方向：具身智能 / Embodied AI"
  location: "Shanghai, China"
  email: "22307140084@m.fudan.edu.cn"
  links:
    - label: "GitHub"
      url: "https://github.com/your-username"
    - label: "Twitter"
      url: "https://twitter.com/yourhandle"

# 页面配置
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# 语法高亮器
highlighter: rouge

# 导航页（在侧边栏或导航显示）
header_pages:
  - index.md
  - about.md

# 分页
paginate: 5
paginate_path: "/page:num/"

# 其他可选项
exclude:
  - Gemfile.lock

sass:
  style: compressed
  load_paths:
    - _sass
