# 基本信息
title: "Embodied Intelligence Notes"
description: "Notes on Embodied Intelligence"
url: "https://daisy-butter.github.io/ruihanwu.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
include_navbar_skip_links: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 作者信息
author:
  name: "Ruihan Wu"
  avatar: "/assets/images/avatar.jpg"
  bio: "Researching Embodied Intelligence, World Models, and Robotics."
  location: "Shanghai, China"
  email: "22307140084@m.fudan.edu.cn"
  links:
    - label: "GitHub"
      url: "https://github.com/Daisy-butter"

# Markdown 与数学公式
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# 语法高亮
highlighter: rouge

# 导航页
header_pages:
  - about.md

# 分页
paginate: 5
paginate_path: "/page:num/"

# SASS 样式加载
sass:
  style: compressed
  load_paths:
    - _sass

# 其他
exclude:
  - Gemfile.lock
