name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: |
          gem install bundler
          bundle init
          echo 'gem "jekyll", "~> 4.3"' >> Gemfile
          echo 'gem "minimal-mistakes-jekyll"' >> Gemfile
          echo 'gem "jekyll-feed"' >> Gemfile
          echo 'gem "jekyll-seo-tag"' >> Gemfile
          echo 'gem "jekyll-paginate"' >> Gemfile
          bundle install
          bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
